set(_AMENT_PACKAGE_NAME "diseno_ntarobot")
set(diseno_ntarobot_VERSION "0.1.0")
set(diseno_ntarobot_MAINTAINER "elio <eliotrianar95@gmail.com>")
set(diseno_ntarobot_BUILD_DEPENDS )
set(diseno_ntarobot_BUILDTOOL_DEPENDS "ament_cmake")
set(diseno_ntarobot_BUILD_EXPORT_DEPENDS )
set(diseno_ntarobot_BUILDTOOL_EXPORT_DEPENDS )
set(diseno_ntarobot_EXEC_DEPENDS "robot_state_publisher" "joint_state_publisher_gui" "rviz2" "ros2launch")
set(diseno_ntarobot_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(diseno_ntarobot_GROUP_DEPENDS )
set(diseno_ntarobot_MEMBER_OF_GROUPS )
set(diseno_ntarobot_DEPRECATED "")
set(diseno_ntarobot_EXPORT_TAGS)
list(APPEND diseno_ntarobot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
