set(_AMENT_PACKAGE_NAME "solver_untils")
set(solver_untils_VERSION "0.0.0")
set(solver_untils_MAINTAINER "elio <elio@todo.todo>")
set(solver_untils_BUILD_DEPENDS "geometry_msgs")
set(solver_untils_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(solver_untils_BUILD_EXPORT_DEPENDS "geometry_msgs")
set(solver_untils_BUILDTOOL_EXPORT_DEPENDS )
set(solver_untils_EXEC_DEPENDS "rosidl_default_runtime" "geometry_msgs")
set(solver_untils_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(solver_untils_GROUP_DEPENDS )
set(solver_untils_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(solver_untils_DEPRECATED "")
set(solver_untils_EXPORT_TAGS)
list(APPEND solver_untils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
